### ISSUE TITLE
Question about attack.py

### ISSUE THREAD

**Issue by titaniumrain** [HarrialX/GraphBackdoor#2]
Hi folks,

Quick question regarding a specific point I am struggling to understand in attack.py

The code (line 105-124 of attack.py) is quoted for self-contained purpose.

```
105                toponet, featnet = gta.train_gtn(
106                    self.args, model, toponet, featnet,
107                    pset, nset, topomask_train, featmask_train, 
108                    init_dr_train, bkd_dr_train, Ainput_train, Xinput_train)
109               
110                # get new backdoor datareader for training based on well-trained generators
111               for gid in bkd_gids_train:
112                    rst_bkdA = toponet(
113                        Ainput_train[gid], topomask_train[gid], self.args.topo_thrd, 
114                        self.cpu, self.args.topo_activation, 'topo')
115                    rst_bkdA = recover_mask(nodenums[gid], topomask_train[gid], 'topo')
116                    bkd_dr_train.data['adj_list'][gid] = torch.add(
117                        rst_bkdA, init_dr_train.data['adj_list'][gid])
118                
119                    rst_bkdX = featnet(
120                        Xinput_train[gid], featmask_train[gid], self.args.feat_thrd, 
121                        self.cpu, self.args.feat_activation, 'feat')
122                    rst_bkdX = recover_mask(nodenums[gid], featmask_train[gid], 'feat')
123                    bkd_dr_train.data['features'][gid] = torch.add(
124                        rst_bkdX, init_dr_train.data['features'][gid]) 
```

My question is on the variable **rst_bkdA** at line 112 and line 115.

It looks like that line 112 uses the trained toponet to generate backdoor graphs, but it was not used at all as the same variable is immediately rewritten at line 115. In this case, why do we need the code from line 112 to 114?

The same question applies to variable **rst_bkdX**

Any insights?

Cheers,

V

**Comment by zhaohan-xi** [comment]
Hi @titaniumrain , we thank you for pointing out this issue. When we reorganized the codes, we mistakenly reassigned the generated adjacency matrix (rst_bkdA) and feature matrix (rst_bkdX) with something irrelevant. What we want to do is only diminishing the matrix from a uniform size to the original size (corresponding to original A and X). Now the codes are updated, please simply play with the new codes :)

**Comment by titaniumrain** [comment]
@HarrialX Truly appreciated! We will give the update a go and circle back feedback if any. The ticket will be closed accordingly. Thanks again.
